{
    "name": "update_from_csv",
    "summary": """Update from csv files""",
    "description": """Update data from csv files""",
    "author": "Jorels SAS",
    "website": "",
    "license": "LGPL-3",
    "category": "Tools",
    "version": "1.0.0.1",
    "images": ["static/images/main_screenshot.png"],
    "support": "",
    "depends": ["base"],
    "data": [],
    "installable": True,
}
